version: 1.0

description: Configuration Change Workflow

input:
  - hostname
  - driver
  - message
  - username

vars:
  - stdout: ""
  - stderr: ""

tasks:
  send_detected_email:
    action: core.sendmail
    input:
      to: "{{ st2kv('system.napalm_remotebackup_mailto') }}"
      from: "{{ st2kv('system.napalm_remotebackup_mailfrom') }}"
      subject: "Stackstorm detected a configuration change on {{ ctx('hostname') }} by {{ ctx('username') }}."
      content_type: "text/plain"
      body: "\r\n\r\nThe following syslog triggered this event: {{ ctx('message') }}\r\n\r\n"
    next:
      - when: "{{ succeeded() }}"
        do: backup_device
      - when: "{{ failed() }}"
        do: notify_on_error

  backup_device:
    action: "core.remote"
    input:
      cmd: "{{ st2kv('system.napalm_remotebackup_cmd') }} {{ ctx('hostname') }} {{ ctx('driver') }}"
      username: "{{ st2kv('system.napalm_remotebackup_user') }}"
      private_key: "/home/stanley/.ssh/stanley_rsa"
      hosts: "{{ st2kv('system.napalm_remotebackup_host') }}"
    next:
      - when: "{{ succeeded() }}"
        publish:
          - stdout: "{{ result()[st2kv('system.napalm_remotebackup_host')].stdout }}"
          - sterr: "{{ result()[st2kv('system.napalm_remotebackup_host')].stdout }}"
        do: send_complete_email
      - when: "{{ failed() }}"
        do: notify_on_error

  send_complete_email:
    action: core.sendmail
    input:
      to: "{{ st2kv('system.napalm_remotebackup_mailto') }}"
      from: "{{ st2kv('system.napalm_remotebackup_mailfrom') }}"
      subject: "Stackstorm completed a backup of {{ ctx('hostname') }}."
      content_type: "text/plain"
      body: "\r\nThe following syslog triggered this event: {{ ctx('message') }}\r\n\r\n
            \r\n{{ ctx('stderr') }}\r\n
            \r\n{{ ctx('stdout') }}\r\n
            \r\n\r\n"

  notify_on_error:
    action: core.sendmail
    input:
      to: "{{ st2kv('system.napalm_actionerror_mailto') }}"
      from: "{{ st2kv('system.napalm_actionerror_mailfrom') }}"
      subject: "Stackstorm device backup workflow error"
      body: "Something went wrong with the device backup workflow. Check stackstorm for the error. Execution ID {{ ctx('st2').action_execution_id }}\r\n\r\n"
    next:
      - do: fail

output:
  - stdout: "{{ ctx('stdout') }}"
  - stderr: "{{ ctx('stderr') }}"
