---
  name: "configuration_change"
  enabled: true
  description: "Webhook which handles when a device has been configured and changes commited"

  trigger:
    type: "core.st2.webhook"
    parameters:
      url: "napalm_conf_change"

  criteria: {}

  action:
    ref: napalm.configuration_change_workflow
    parameters:
      hostname: "{{trigger.body.logsource}}"
      host_ip: "{{trigger.body.host}}"
      driver: "{{trigger.body.os_type}}"
      message: "{{trigger.body.message}}"
      username: "{{trigger.body.username}}"
      
